language: java
jdk:
  - oraclejdk11
  - openjdk11
services:
  - docker

jobs:
  include:
    - stage: test
      script: ./mvnw clean test
    - stage: build
      script: ./mvnw package
      branches:
        only:
          - master